### ISSUE TITLE
Error since update

### ISSUE THREAD

**Issue by dorel14** [DonDebonair/slack-machine#157]
Hello 
I've updated slack machine to latest release and i have this error after launching a scheduled message
~~~
[2019-03-12 21:35:00][DEBUG] apscheduler.scheduler base.py:_process_jobs:1017 | Next wakeup is due at 2019-03-13 21:35:00+01:00 (in 86399.996633 seconds)
Traceback (most recent call last):
  File "/home/pi/projets/supportBot/bin/slack-machine", line 10, in <module>
    sys.exit(main())
  File "/home/pi/projets/supportBot/lib/python3.5/site-packages/machine/bin/run.py", line 14, in main
[2019-03-12 21:35:00][INFO] apscheduler.executors.default base.py:run_job:144 | Job "suiviMeteo.humeurJour (trigger: cron[hour='21', minute='35'], next run at: 2019-03-13 21:35:00 CET)" executed successfully
    bot.run()
  File "/home/pi/projets/supportBot/lib/python3.5/site-packages/machine/core.py", line 219, in run
    self._dispatcher.start()
  File "/home/pi/projets/supportBot/lib/python3.5/site-packages/machine/dispatch.py", line 29, in start
    for event in self._client.rtm_read():
  File "/home/pi/projets/supportBot/lib/python3.5/site-packages/slackclient/client.py", line 235, in rtm_read
    json_data = self.server.websocket_safe_read()
  File "/home/pi/projets/supportBot/lib/python3.5/site-packages/slackclient/server.py", line 278, in websocket_safe_read
    data += "{0}\n".format(self.websocket.recv())
  File "/home/pi/projets/supportBot/lib/python3.5/site-packages/websocket/_core.py", line 310, in recv
    opcode, data = self.recv_data()
  File "/home/pi/projets/supportBot/lib/python3.5/site-packages/websocket/_core.py", line 327, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/home/pi/projets/supportBot/lib/python3.5/site-packages/websocket/_core.py", line 340, in recv_data_frame
    frame = self.recv_frame()
  File "/home/pi/projets/supportBot/lib/python3.5/site-packages/websocket/_core.py", line 374, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/home/pi/projets/supportBot/lib/python3.5/site-packages/websocket/_abnf.py", line 361, in recv_frame
    self.recv_header()
  File "/home/pi/projets/supportBot/lib/python3.5/site-packages/websocket/_abnf.py", line 309, in recv_header
    header = self.recv_strict(2)
  File "/home/pi/projets/supportBot/lib/python3.5/site-packages/websocket/_abnf.py", line 396, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "/home/pi/projets/supportBot/lib/python3.5/site-packages/websocket/_core.py", line 449, in _recv
    return recv(self.sock, bufsize)
  File "/home/pi/projets/supportBot/lib/python3.5/site-packages/websocket/_socket.py", line 81, in recv
    bytes_ = sock.recv(bufsize)
  File "/usr/lib/python3.5/ssl.py", line 922, in recv
    return self.read(buflen)
  File "/usr/lib/python3.5/ssl.py", line 799, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.5/ssl.py", line 585, in read
    v = self._sslobj.read(len)
BlockingIOError: [Errno 11] Resource temporarily unavailable
~~~
`

**Comment by DandyDev** [comment]
I'm sorry to hear that. I suggest you roll back to the previous version for now. Then I will check what goes wrong.

**Comment by preludedrew** [comment]
I've been running into this too. No pattern that I could see. Sometimes it would happen after 8m of connectivity, sometimes it was 50m... It seemed to be a race between the rtm_read() and the task/event thread. Moving the time.sleep to 1 second instead of a 10/th of a second has so far proven to work. I don't see any reason why 1 second would interfere with any timing, and .1 seemed a little arbitrary to me. I'll test it out for a few days and submit a PR if it's good.

**Comment by preludedrew** [comment]
Ran that over the weekend and it definitely helped, but I found ~3-4 instances per day.

**Comment by yaelbikel** [comment]
any update on this one? I'm getting this error one in a while
`Traceback (most recent call last):
  File "/home/slackbot.runfiles/armis/deploy/services/slackbot/slack_machine_service.py", line 40, in <module>
    main()
  File "/home/slackbot.runfiles/armis/deploy/services/slackbot/slack_machine_service.py", line 36, in main
    machine.bin.run.main()
  File "/home/slackbot.runfiles/pip__slack_machine_0_18_0_py2_py3_none_any/machine/bin/run.py", line 14, in main
    bot.run()
  File "/home/slackbot.runfiles/pip__slack_machine_0_18_0_py2_py3_none_any/machine/core.py", line 219, in run
    self._dispatcher.start()
  File "/home/slackbot.runfiles/pip__slack_machine_0_18_0_py2_py3_none_any/machine/dispatch.py", line 29, in start
    for event in self._client.rtm_read():
  File "/home/slackbot.runfiles/pip__slackclient_1_3_1_py2_py3_none_any/slackclient/client.py", line 235, in rtm_read
    json_data = self.server.websocket_safe_read()
  File "/home/slackbot.runfiles/pip__slackclient_1_3_1_py2_py3_none_any/slackclient/server.py", line 278, in websocket_safe_read
    data += "{0}\n".format(self.websocket.recv())
  File "/home/slackbot.runfiles/pip__websocket_client_0_56_0_py2_py3_none_any/websocket/_core.py", line 313, in recv
    opcode, data = self.recv_data()
  File "/home/slackbot.runfiles/pip__websocket_client_0_56_0_py2_py3_none_any/websocket/_core.py", line 330, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/home/slackbot.runfiles/pip__websocket_client_0_56_0_py2_py3_none_any/websocket/_core.py", line 343, in recv_data_frame
    frame = self.recv_frame()
  File "/home/slackbot.runfiles/pip__websocket_client_0_56_0_py2_py3_none_any/websocket/_core.py", line 377, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/home/slackbot.runfiles/pip__websocket_client_0_56_0_py2_py3_none_any/websocket/_abnf.py", line 361, in recv_frame
    self.recv_header()
  File "/home/slackbot.runfiles/pip__websocket_client_0_56_0_py2_py3_none_any/websocket/_abnf.py", line 309, in recv_header
    header = self.recv_strict(2)
  File "/home/slackbot.runfiles/pip__websocket_client_0_56_0_py2_py3_none_any/websocket/_abnf.py", line 396, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "/home/slackbot.runfiles/pip__websocket_client_0_56_0_py2_py3_none_any/websocket/_core.py", line 452, in _recv
    return recv(self.sock, bufsize)
  File "/home/slackbot.runfiles/pip__websocket_client_0_56_0_py2_py3_none_any/websocket/_socket.py", line 100, in recv
    bytes_ = sock.recv(bufsize)
  File "/usr/lib/python3.5/ssl.py", line 922, in recv
    return self.read(buflen)
  File "/usr/lib/python3.5/ssl.py", line 799, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.5/ssl.py", line 585, in read
    v = self._sslobj.read(len)
BlockingIOError: [Errno 11] Resource temporarily unavailable`

**Comment by enver** [comment]
I think this issue occurs when the connection to slack gets interrupted. It would be great that bot tries to reconnect and survives occasional network issues/service disruptions, rather than crashing.

**Comment by DandyDev** [comment]
@dorel14 @preludedrew @yaelbikel @enver are you still experiencing this issue? I've pushed some updates that should generally make slack-machine more reliable. Among other things, it uses the newest Slack SDK for Python
